### PR TITLE
add scCODA package

### PR DESCRIPTION
**Pull request by mikelkou**

### CODE REVIEW

**Comment by grst** [comment]
as far as i can tell this has tests ,but no CI.

**Comment by grst** [comment]
@johannesostner, I see a `.travis.yml` file, but there's no CI badge and it doesn't seem to run on PRs :thinking:

**Comment by johannesostner** [comment]
We set up some rudimentary CI with travis a long time ago, but discontinued it after some time.
We are currently in the process of reimplementing scCODA as part of a full scverse package anyways, including CI, of course. Thus I'm unsure if it's necessary to add scCODA to this repository.

**Comment by grst** [comment]
Ok, then feel free to make a new PR once the reimplemented version is ready

**Pull request closed without merging**
