### PR TITLE
Request to add Multivelo to scverse

### PR DESCRIPTION
**Pull request by jacobrepucci**
Name of the tool: Multivelo

Short description: A mechanistic model of gene expression that extends the popular RNA velocity framework by incorporating epigenomic data.

How does the package use scverse data structures (please describe in a few sentences): Multivelo is designed to process data stored in AnnData objects. In addition, it uses Scanpy tools in order to process the data at various steps in our functions.

- [x]  The code is publicly available under an [OSI-approved](https://opensource.org/licenses/alphabetical) license
- [x]  The package provides versioned releases
- [x]  The package can be installed from a standard registry (e.g. PyPI, conda-forge, bioconda)
- [x]  The package uses automated software tests and runs them via continuous integration (CI)
- [x]  The package provides API documentation via a website or README
- [x]  The package uses scverse datastructures where appropriate (i.e.anndata/mudata and their modality-specific extensions)
- [x]  I am the author or maintainer of the tool and agree on listing the package on the scverse website
- [x]  I would like this package to be announced on scverse channels (zulip, discourse, twitter) [@LabWelch]
- [x]  The package provides tutorials (or "vignettes") that help getting users started quickly

### CODE REVIEW

**Comment by grst** [comment]
Hi @jacobrepucci, 

thanks for your request! 

I have a couple of comments regarding the requirements: 
 * while you have versioned releases on PyPI, please also mark them as tags or releases in GitHub. 
 * The test suite seems to cover only a single function of your entire API. While we do not have strict cutoffs on coverage at the moment, your test suite should definitely cover most of your functions. As an alternative (or addition) to unit tests, you could run an entire notebook on CI as a high-level functionality test (aka "smoke test"). 
 * Tests do not seem to be executed automatically by continuous integration (or at least I don't see any of the common config files)

Minor points (not relevant for the inclusion): 
 * I think you could structure the readme better by making separate sections for installation, docs and tutorials. Especially the installation instructions are hidden in a huge block of text. You can see a best practice example in our [demo repository](https://github.com/scverse/cookiecutter-scverse-instance). 
 * The link to the tutorial from the README is broken.

**Comment by jacobrepucci** [comment]
Hi Gregor,

Thanks for the comments! These are helpful.

When you mention "Tests do not seem to be executed automatically by continuous integration," do you mean that I should be running my unit tests via pre-commit.ci? Or just that pre-commit should be run automatically with commits/pushes (using the default_stages hook)?

Thanks,
Jacob

**Comment by grst** [comment]
pre-commit CI is not really suitable for these kind of tests. This is usually done using [GitHub actions](https://docs.github.com/en/actions/quickstart). 

If you are unfamiliar with these kind of things I recommend checking out our [cookiecutter template](https://github.com/scverse/cookiecutter-scverse). It sets up a repository with automated tests, docs builds, pre-commit checks ready-to go.
There's also [documentation how to work with the template](https://cookiecutter-scverse-instance.readthedocs.io/en/latest/template_usage.html)

**Comment by jacobrepucci** [comment]
Hi again Gregor,

I made the requested changes to Multivelo, and in that same time we also incremented to version 0.1.3. Are there any more changes to be made or is Multivelo fit for adding to scverse?

Thanks,
Jacob

**Comment by jacobrepucci** [comment]
Hi Gregor,

When will the scverse/ecosystem-packages repo update with Multivelo? Our team is hoping to announce the addition on social media when it goes up!

-Jacob

**Comment by grst** [comment]
Sorry for the delay. I merged it now. I mostly kept it open as a reminder to do the social media announcement on our part -- and we were still figuring out access rights for twitter for the right person.

**Pull request merged**
