### PR TITLE
add pychromVAR

### PR DESCRIPTION
**Pull request by lzj1769**
Name of the tool: pychromVAR

Short description: A python package for chromVAR

How does the package use scverse data structures (please describe in a few sentences): 
The package uses Anndata and Mudata for estimating motifs binding sites accessibility deviations from scATAC-seq.

-   [x] The code is publicly available under an [OSI-approved](https://opensource.org/licenses/alphabetical) license
-   [x] The package provides versioned releases
-   [x] The package can be installed from a standard registry (e.g. PyPI, conda-forge, bioconda)
-   [x] The package uses automated software tests and runs them via continuous integration (CI)
-   [x] The package provides API documentation via a website or README
-   [x] The package uses scverse datastructures where appropriate (i.e.anndata/mudata and their modality-specific extensions)
-   [x] I am the author or maintainer of the tool and agree on listing the package on the scverse website

### CODE REVIEW

**Comment by grst** [comment]
Hi @lzj1769, 

thanks for adding this! I had a quick glance at the repo and couldn't see any continuous integration (e.g. github actions) set up. Also the test suite only contains only a single test... Any chance you can expand that a little bit before we add it as an ecosystem package? 

Best, 
Gregor

**Comment by lzj1769** [comment]
@grst 

Thanks for the info. 
I will try to fix these issues.

**Comment by lzj1769** [comment]
Hi Gregor, 

I have added continuous integration and more test scripts in the package. Also, the documentation now includes an API section: https://pychromvar.readthedocs.io/en/latest/api.html

Can you check it out? 
Please let me know if there is anything missing.

Thanks and best,
Zhijian

**Review by grst — APPROVED** [review]
LGTM now! Thanks!

**Pull request merged**
