### PR TITLE
gssnng

### PR DESCRIPTION
**Pull request by Gibbsdavidl**
Mandatory
Name of the tool: gssnng

Short description: This tool uses the nearest neighbor graph of cells --within question driven groups-- for matrix smoothing to produce high quality gene set scores on a per-cell, per-group, level which is useful for visualization and statistical analysis.

How does the package use scverse data structures (please describe in a few sentences): Adds the gene set scores into the AnnData obs table for plotting with scanpy.pl functions.

 The code is publicly available under an [OSI-approved](https://opensource.org/licenses/alphabetical) license  [Yes]
 The package provides versioned releases [Yes]
 The package can be installed from a standard registry (e.g. PyPI, conda-forge, bioconda) [Yes]
 The package uses automated software tests and runs them via continuous integration (CI)  [Yes]
 The package provides API documentation via a website or README  [Yes]
 The package uses scverse datastructures where appropriate (i.e. AnnData, MuData or SpatialData and their modality-specific extensions) [Yes]
 I am an author or maintainer of the tool and agree on listing the package on the scverse website [Yes]
Recommended
 Please announce this package on scverse communication channels (zulip, discourse, twitter) ok
 Please tag the author(s) these announcements. Handles (e.g. @scverse_team) to include are:
Twitter: @gibbsdavidl
Zulip:
Discourse:
Mastodon:
 The package provides tutorials (or "vignettes") that help getting users started quickly [Yes]
 The package uses the [scverse cookiecutter template](https://github.com/scverse/cookiecutter-scverse). [No]

### CODE REVIEW

**Comment by grst** [comment]
Hi @Gibbsdavidl, 

thanks for submitting the package, looks mostly good, just see my two comments below: 

Regarding the tests, I was wondering if it would make sense to have the `example_script.py`, `geneset_overlap_test.py`, `score_cells_test.py` and `ssgsea_test.py` be executed by pytest on CI as well. They don't seem to be included in recent CI runs and it looks like they are intended for manual execution from the command line. Even if those tests don't check for the correctness of results, it is still useful to ensure that the full workflow can be ran without errors. 

> The package provides API documentation via a website or README

Here I just wanted to check if `score_cells.with_gene_sets` is the only user-facing method of the package. If yes, what you have in the README is completely fine. If you have more functions that the user should know about (what about `.run_gssng()`?), please add them to the README, or consider using Sphinx/Readthedocs for the API Documentation (e.g. https://scirpy.scverse.org/en/latest/api.html)

**Comment by Gibbsdavidl** [comment]
Hello!  Just checking in here... I will be updating the tests and adding run_gssnng to the documentation. Thank you!

**Comment by Gibbsdavidl** [comment]
Hi there @grst ,

Took awhile(!), but I have updated our readthedocs to include the main functions and now pytest runs the example scripts with github actions.  

I think that should do it.  :-)

https://gssnng.readthedocs.io/en/latest/

-dave

**Review by Zethson — APPROVED** [review]

**Comment by Zethson** [comment]
Great, thank you!

**Comment by Gibbsdavidl** [comment]
If it hasn't been announced, it would be greatly appreciated!  :-)

**Pull request merged**
